### ISSUE TITLE
Submit to pypi

### ISSUE THREAD

**Issue by schwa** [BonsaiDen/twitter-text-python#11]
Any chance you could submit this to the Python Cheeseshop? http://pypi.python.org/pypi

**Comment by BonsaiDen** [comment]
Hey there,

@ianozsvald is actually working on taking over the library and submitting it to PyPi in the process.

**Comment by ianozsvald** [comment]
Hello Ivo, @schwa. I'm in the process of submitting it, this is my first PyPI submission so during my testing I accidentally pushed a version to PyPI:
http://pypi.python.org/pypi?name=twitter-text-python&version=1.0&:action=display
and I have some tweaks and a license change (along with some docs) to add. I'm hoping to finalise it this week (this weekend was spent writing up my PyCon tutorial which uses this library).

**Comment by ianozsvald** [comment]
Official release (v1.0.0.2) now online:
http://pypi.python.org/pypi/twitter-text-python/

**Comment by schwa** [comment]
Awesome. Thank you very much.
