### ISSUE TITLE
Can not handle short domain

### ISSUE THREAD

**Issue by ayanamist** [BonsaiDen/twitter-text-python#4]
Twitter will parse "name.com" as a seperate link and convert it to a t.co one, however this module does not do as the same.

**Comment by robmadden** [comment]
Here is an example of a tweet affected by this:

"Dinos cuantos goles nos llevaran al triunto y disfruta esta promo! #Vivelaroja #viveavanzado http://bit.ly/11gKAXD pic.twitter.com/FBeLFs29kl"

Twitter-text-js will parse these correctly, but the ruby and python versions do not.

**Comment by BonsaiDen** [comment]
Hey there :) I'm no longer maintaining this library, please file this bug against: https://github.com/ianozsvald/twitter-text-python
